# 1. Definición del Upstream (Balanceador)
# Nginx usará el nombre del servicio de Docker para encontrar las IPs de las réplicas
upstream my_cluster {
    server app-principal:80;
}

# 2. Servidor Virtual para app1.test
server {
    listen 80;
    server_name app1.test;

    location / {
        proxy_pass http://my_cluster;
        
        # Configuraciones de Proxy (Cabeceras para que el backend sepa quién le habla)
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # Alta Disponibilidad (Failover)
        # Si una réplica falla, Nginx salta automáticamente a la siguiente
        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
    }
}

# 3. Servidor Virtual para app2.test (Opcional)
server {
    listen 80;
    server_name app2.test;

    location / {
        # Aquí podrías apuntar a otro upstream o al mismo
        proxy_pass http://my_cluster;
    }
}
